### ISSUE TITLE
stacks.js / blockstack.js / @stacks/{auth,storage} docs missing

### ISSUE THREAD

**Issue by dantrevino** [blockstack/docs#874] opened 2020-11-05 20:33 UTC
The detailed developer documentation that used to be available from the Github repo is now nowhere to be found.  Details of function return errors, callbacks, etc are critical to developers.

**Comment by agraebe** [comment] 2020-11-05 22:00
seems a duplicate of https://github.com/blockstack/docs/issues/875

**Closed by agraebe** 2020-11-05 22:00 UTC
