### ISSUE TITLE
Stacks integration guide: Add reference page to list key properties of Stacks 2.0

### ISSUE THREAD

**Issue by agraebe** [blockstack/docs#780] opened 2020-09-18 21:34 UTC
As [suggested by @jeffdomke ](https://github.com/blockstack/docs/pull/757#pullrequestreview-491677541) we could add a reference page to the Stacks 2.0 integration guide this page, inspired by [this technical spec](https://monerodocs.org/technical-specs/).

This page could include:
- type of mining mechanism (PoX)
- UTXO or accounts
- type of encryption and serialization
- blocktime
-  token name and how it is divided

**Comment by agraebe** [comment] 2020-09-18 21:35
@yknl @diwakergupta please add to the list if you have more ideas. I can include this in the next iteration of the guide (not #757)

**Comment by GinaAbrams** [comment] 2020-10-16 14:20
Is this the best place to put this? Adding a list of questions Xan sent over: 

1. What are the up to date, confirmed basic stx mining parameters? By parameters I mean things like block reward amount, block time, mining support transactions, mining pools, etc...
2. What are the up to date, confirmed basic stacking parameters? Things like cycle length, minimum calculation, reward addresses per block, changes to either the prepare or reward phases, etc...

On Stacking Earnings Model: 
- Is 2 stacking addresses per block the new confirmed number?
- Explanation of how the "PoX Transaction Size on BTC Chain" is calculated. Most of the numbers are hardcoded.
- Likewise an explanation of how the "Trx Cost per Miner per Block" is calculated.
- What does "Miner's Share of Excess Value" represent?
- Confirming the new Stacking cycle length is 2 weeks?

**Comment by diwakergupta** [comment] 2020-10-16 15:17
I'll answer as many of these I can, and include pointers to authoritative source:

- block reward: described in this [forum post](https://forum.blockstack.org/t/pox-consensus-and-stx-future-supply/11232) and detailed in [this spreadsheet](https://docs.google.com/spreadsheets/d/17hbPuFXW-VIxcJhH3Z289NH4Qef5CospQlP1VXA5Jfc/edit#gid=861027803). Summary is 1000 STX/block for first 4 yrs; 500 STX/block for following 4 yrs; 250 for the 4 yrs after that; and then 125 STX/block in perpetuity after that.
- block time: Stacks blockchain produces blocks at the same rate as the underlying burnchain. Bitcoin blocks are produced roughly once every 10min, so that's will be the rate for Stacks 2.0 mainnet.
- block reward maturity window: [100 blocks](https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/db/mod.rs#L500), meaning if a miner wins a block, they will earn the coinbase reward for that block after 100 blocks have elapsed.
- "mining support transactions" / "mining pools": not sure exactly what the question is here, or what parameters are being asked for.
- Stacking parameters: 2 reward addresses / block; reward cycle 2000 blocks (~2 weeks) for a total of 4000 reward slots. Once this [PR is merged](https://github.com/blockstack/stacks-blockchain/pull/1975), SIP-007 will reflect these choices.
- Stacking threshold: also as described in SIP-007. Basically the threshold is 0.025% of the participating amount of STX when participation is between 25% and 100% and when participation is below 25%, the threshold level is always 0.00625 of the liquid supply of STX.

@GinaAbrams for questions on the Stacking earnings model, I defer to @jessesoslow -- in general, the spreadsheet is pretty self-explanatory. For instance, "Trx Cost per Miner per Blocks" and "Trx Cost per Miner per Block" are calculated using other fields in the sheet.

**Comment by GinaAbrams** [comment] 2020-10-16 16:24
Thank you @diwakergupta!! 🙏

**Comment by jessesoslow** [comment] 2020-10-16 17:48
I'd agree that the questions related to the spreadsheet aren't hard coded in the spreadsheet and their equations can be pulled directly from the spreadsheet.  Nevertheless, here are some answers to the spreadsheet-specific questions:

> Explanation of how the "PoX Transaction Size on BTC Chain" is calculated. Most of the numbers are hardcoded.

We're calculating the number of bytes the transaction needs to be for a PoX transaction.  The equation in the spreadsheet is 250 bytes + 33*(n + 1) bytes, where n is the number of addresses the PoX transaction is sending to.  Since each PoX transaction is sending to 2 addresses, n is 2, and the total expected number of bytes for a PoX transaction will be 349.  This shouldn't change.  The actual cost of a PoX transaction can then be estimated by looking at current estimates for satoshis / byte for BTC transactions at any given time.

If the question is _why_ does the size of a PoX transaction equal 250 + 33*(n + 1), then that question would need to be for someone more technical than myself.  I got this equation from Aaron.

> Likewise an explanation of how the "Trx Cost per Miner per Block" is calculated.

As alluded to above, this is calculated as the number of bytes / transaction times an estimate of satoshis / byte. You then have a number of satoshis per transaction, which is then converted to USD based on the USD value estimate of BTC that is included in the sheet.

> What does "Miner's Share of Excess Value" represent?

The total amount of the coinbase plus the STX tx fees paid in a block is the "Total Reward" for a miner.  The "Excess Value" represents the difference between the value of the "Total Reward" and the total BTC fees that miners pay to send their transactions for a round.

Excess Value will be broken up between two parties:  stackers and miners.  If 100% of excess value goes to miners, this essentially means that miners are only sending the value of transaction fees and in return they're getting the coinbase plus STX transaction fees.  If 100% of excess value goes to stackers, then miners will be sending BTC value essentially equal to the value of the Total Reward.

I think it's probably a fair assumption that miners will be sending BTC, in total with fees, slightly less than the Total Reward.

**Comment by agraebe** [comment] 2020-11-02 21:10
info from this post should be included: https://forum.blockstack.org/t/stacks-2-0-proof-of-transfer-rolled-out-on-testnet/11219/4?u=agraebe

**Comment by diwakergupta** [comment] 2020-11-05 16:40
@agraebe are you actively working on this? I'd like to help: if you have something in-progress, feel free to share!

**Comment by agraebe** [comment] 2020-11-05 17:03
thanks very much, @diwakergupta  🙏 I didn't get to drafting anything up yet

**Closed** 2020-11-11 15:58 UTC
Labels: documentation, enhancement, mainnet
